//! Render a context graph as a readable Markdown project document.

use std::fmt::Write;

use blink_context::ContextGraph;

pub fn render(graph: &ContextGraph) -> String {
    let mut out = String::new();
    let p = &graph.project;

    let _ = writeln!(out, "# Blink Context — {}", p.name);
    out.push('\n');
    let _ = writeln!(
        out,
        "_Generated by `blink export` from measured project facts — every count and reference below is derived from real files._"
    );
    out.push('\n');

    // Overview.
    out.push_str("## Overview\n\n");
    let _ = writeln!(out, "- **Language:** {}", p.language);
    if let Some(fw) = &p.framework {
        let _ = writeln!(out, "- **Framework:** {fw}");
    }
    let _ = writeln!(out, "- **Package manager:** {}", p.package_manager);
    if p.is_workspace {
        let _ = writeln!(out, "- **Workspace:** yes");
    }
    let _ = writeln!(
        out,
        "- **Files:** {} ({} source)",
        graph.stats.files, graph.stats.source_files
    );
    let _ = writeln!(out, "- **Lines:** {}", graph.stats.lines);
    let _ = writeln!(out, "- **Symbols:** {}", graph.stats.symbols);
    let _ = writeln!(out, "- **Size:** {}", human_size(graph.stats.size_bytes));
    match &graph.config.file {
        Some(f) => {
            let _ = writeln!(out, "- **Config:** `{f}`");
        }
        None => {
            let _ = writeln!(out, "- **Config:** none");
        }
    }
    out.push('\n');

    // Areas.
    if !graph.areas.is_empty() {
        out.push_str("## Areas\n\n");
        out.push_str("| Area | Files | Lines | Symbols | Languages |\n");
        out.push_str("| --- | ---: | ---: | ---: | --- |\n");
        for area in graph.ranked_areas() {
            let langs = if area.languages.is_empty() {
                "—".to_string()
            } else {
                area.languages.join(", ")
            };
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} | {} |",
                area.path, area.files, area.lines, area.symbols, langs
            );
        }
        out.push('\n');
    }

    // Dependencies.
    if !graph.dependencies.is_empty() {
        out.push_str("## Dependencies\n\n");
        for dep in &graph.dependencies {
            let dev = if dep.dev { " _(dev)_" } else { "" };
            let _ = writeln!(out, "- `{}` {}{}", dep.name, dep.version, dev);
        }
        out.push('\n');
    }

    // Commands.
    if !graph.commands.is_empty() {
        out.push_str("## Commands\n\n");
        out.push_str("| Name | Source | Command |\n");
        out.push_str("| --- | --- | --- |\n");
        for cmd in &graph.commands {
            let _ = writeln!(
                out,
                "| `{}` | {} | `{}` |",
                cmd.name, cmd.source, cmd.command
            );
        }
        out.push('\n');
    }

    // Area relationships.
    let edges = graph.area_edges();
    if !edges.is_empty() {
        out.push_str("## Area relationships\n\n");
        out.push_str("How the areas reference one another (by resolved import count):\n\n");
        for edge in edges.iter().take(25) {
            let _ = writeln!(out, "- `{}` → `{}` ({})", edge.from, edge.to, edge.count);
        }
        out.push('\n');
    }

    out
}

fn human_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KB", "MB", "GB"];
    let mut size = bytes as f64;
    let mut unit = 0;
    while size >= 1024.0 && unit < UNITS.len() - 1 {
        size /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{bytes} B")
    } else {
        format!("{size:.1} {}", UNITS[unit])
    }
}
