use std::fmt::Write as _;

use anyhow::{Context, Result};
use blink_analyzer::format_bytes;
use blink_core::ProjectDetector;
use blink_workflow::tasks;

use crate::cli::DocsArgs;
use crate::indexing::ensure_index;
use crate::ui;

pub fn run(args: DocsArgs) -> Result<()> {
    let project = ProjectDetector::new()
        .detect(&args.path)
        .with_context(|| format!("could not inspect {}", args.path.display()))?;
    let index = ensure_index(&args.path)?;
    let task_list = tasks::discover(&args.path);

    let mut md = String::new();
    let _ = writeln!(md, "# {}", project.name);
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "<!-- Generated by `blink docs` from measured project facts. Review and edit before publishing. -->"
    );
    let _ = writeln!(md);

    let _ = writeln!(md, "## Overview");
    let _ = writeln!(md);
    let _ = writeln!(md, "- **Language:** {}", project.language);
    if project.framework.to_string() != "None" {
        let _ = writeln!(md, "- **Framework:** {}", project.framework);
    }
    let _ = writeln!(md, "- **Package manager:** {}", project.package_manager);
    if project.is_workspace {
        let _ = writeln!(md, "- **Layout:** workspace / monorepo");
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## Statistics");
    let _ = writeln!(md);
    let _ = writeln!(md, "| Metric | Value |");
    let _ = writeln!(md, "| --- | --- |");
    let _ = writeln!(md, "| Files | {} |", index.file_count());
    let _ = writeln!(md, "| Lines of code | {} |", index.total_lines());
    let _ = writeln!(md, "| Symbols | {} |", index.symbol_count());
    let _ = writeln!(md, "| Size | {} |", format_bytes(index.total_size()));
    let _ = writeln!(
        md,
        "| Direct dependencies | {} |",
        project.dependency_count()
    );
    let _ = writeln!(md);

    let langs = index.language_breakdown();
    if !langs.is_empty() {
        let _ = writeln!(md, "## Languages");
        let _ = writeln!(md);
        let _ = writeln!(md, "| Language | Files | Lines |");
        let _ = writeln!(md, "| --- | --- | --- |");
        for (lang, (files, lines)) in langs {
            let _ = writeln!(md, "| {lang} | {files} | {lines} |");
        }
        let _ = writeln!(md);
    }

    if !task_list.is_empty() {
        let _ = writeln!(md, "## Tasks");
        let _ = writeln!(md);
        let _ = writeln!(md, "| Task | Command | Source |");
        let _ = writeln!(md, "| --- | --- | --- |");
        for task in &task_list {
            let _ = writeln!(
                md,
                "| `{}` | `{}` | {} |",
                task.name, task.command, task.source
            );
        }
        let _ = writeln!(md);
    }

    if let Some(output) = &args.output {
        std::fs::write(output, &md)
            .with_context(|| format!("could not write {}", output.display()))?;
        ui::banner("Blink Docs");
        ui::step(format!("Wrote {}", output.display()));
        println!();
    } else {
        print!("{md}");
    }
    Ok(())
}
